# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [16]:
print('numpy version is', np.__version__)
print(np.show_config())

numpy version is 1.14.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆)

In [17]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [21]:
ms = x.size*x.itemsize
print('memory size of x is %i bytes' %ms)

memory size of x is 80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [30]:
python -c "import numpy as np; np.info(np.add)"

SyntaxError: invalid syntax (<ipython-input-30-113e43e8c33b>, line 1)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [31]:
y = np.zeros(10)
y[4] = 1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [33]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [39]:
z_r = np.flip(z, 0)
print(z_r)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [41]:
X = np.arange(9).reshape((3, 3))
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [49]:
indices = np.nonzero([1, 2, 0, 0, 4, 0])
print(indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [50]:
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [52]:
R = np.random.random((3, 3, 3))
print(R)

[[[0.54203135 0.50980229 0.46912829]
  [0.53613547 0.90456725 0.36337646]
  [0.63723299 0.27400691 0.90705429]]

 [[0.18013927 0.50527053 0.82305416]
  [0.07267869 0.71512947 0.89077332]
  [0.18807292 0.71571825 0.55300429]]

 [[0.5654173  0.5698002  0.41602231]
  [0.66187562 0.06255863 0.66303973]
  [0.90344203 0.00915713 0.95199644]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [54]:
R1 = np.random.random((10, 10))
max_r = R1.max()
min_r = R1.min()
print(min_r, max_r)

0.01821791430024622 0.9989230077874637


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [59]:
v = np.random.random(30)
mean = v.mean()
print(mean)

0.5191588004885473


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [61]:
X = np.ones((6, 6))
X[1:-1, 1:-1] = 0
print(X)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [62]:
X = np.pad(X, pad_width=1, mode='constant', constant_values=0)
print(X)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [64]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [68]:
A = np.diag(1+np.arange(4), k=-1)
print(A)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [89]:
B = np.ones((8, 8))
B[ ::2, ::2 ] = 0
B[ 1::2, 1::2 ] = 0
print(B)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [94]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [97]:
print(np.tile(np.eye(2), (4, 4)))

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [110]:
A = np.random.random((5, 5))
A = A/(np.linalg.norm(A))
print(A)

[[0.23845072 0.36417238 0.31402789 0.18211699 0.2020381 ]
 [0.22306238 0.00473297 0.27398608 0.28065066 0.18907963]
 [0.22303971 0.21416527 0.27309294 0.22904886 0.0362326 ]
 [0.20714953 0.0473873  0.17044495 0.03028299 0.0917401 ]
 [0.06384732 0.08812373 0.16539534 0.1205545  0.1931703 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [112]:
color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [114]:
print(np.dot(np.random.random((5, 3)), np.random.random((3, 2))))

[[0.96775882 1.27202049]
 [0.54595052 0.6392584 ]
 [1.41935576 1.4818753 ]
 [0.78470755 0.83205377]
 [1.17212928 1.20917542]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [123]:
a = np.arange(10)
a[(a>3) & (a<8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [124]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [138]:
Z = np.arange(10)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [141]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [147]:
X = np.random.normal(0, 5, (10, 10))
print (np.copysign(np.ceil(np.abs(X)), X))

[[  7. -12. -10.   6.   3.   1.   1.   9.   2.   3.]
 [ -4.  -3.  -1.   2.   1.  -1.  -3.  -4. -11.  13.]
 [  2.  -4.   8.   2.  -4.  -7.   7.  -4.  -7.  -1.]
 [ -2.  -1.   6.   7.  -4.   4.  -9.  -6.  -3.   6.]
 [ -8.   2.  -1.   1.   1.  -3.   1.   2.  -9.   4.]
 [ 12.  -1.  -1.  -7.   4.   4.  -7.  -3.  -1.   1.]
 [ -3.  -4.  -1.  -7. -11.  10.   1.   3.   5.  -2.]
 [  8.   4.  -6.  -1.   7.  -6.  -3.  -4.   3.  -7.]
 [ 11.  -1.   9.   1.  -4.  -5.   5. -12.  -1.  -5.]
 [  5.  -1.   6.  -2.  -2. -11.  -3.  -6.  -4.  -2.]]


#### 30. How to find common values between two arrays? (★☆☆)

In [150]:
X = np.arange(10)
Y = np.arange(6, 12)
print(np.intersect1d(X, Y))

[6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [169]:
np.seterr(all="ignore")

{'divide': 'ignore', 'invalid': 'ignore', 'over': 'ignore', 'under': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [170]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [172]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2018-05-20 2018-05-21 2018-05-22


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [179]:
july = np.arange('2016-07-01', '2016-08-01', dtype=datetime64)
print(july)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [202]:
A = np.arange(1, 10)
print(A)
B = np.arange(4, 13)
print(B)
np.add(A, B, out=B)
A = A/(-2)
B = A*B
print(B)

[1 2 3 4 5 6 7 8 9]
[ 4  5  6  7  8  9 10 11 12]
[ -2.5  -7.  -13.5 -22.  -32.5 -45.  -59.5 -76.  -94.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [207]:
A = random.normal(0, 15, 5)
print (A.astype(int))
print (np.floor(A))
print (np.ceil(A)-1)
print (A - A % 1)
print (np.trunc(A))

[  8  -3 -10 -11  -9]
[  8.  -4. -11. -12. -10.]
[  8.  -4. -11. -12. -10.]
[  8.  -4. -11. -12. -10.]
[  8.  -3. -10. -11.  -9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [210]:
Z = np.tile(np.arange(5), 5).reshape((5,5))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [217]:
def gen():
    for x in np.random.randint(0, 1000, 10):
        yield x
X = np.fromiter(gen(),dtype=float)
print(X)

[842. 852. 608. 188. 462. 912. 791. 829. 974. 280.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [220]:
Y = np.linspace(0, 1, 11, endpoint=False)[1:]
print(Y)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [222]:
Z = np.sort(random.random(10))
print(Z)

[0.02710082 0.04158997 0.07743897 0.29235223 0.43437123 0.50291337
 0.51733595 0.8289199  0.83138642 0.95656667]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [227]:
A = np.random.randint(0, 100, 10)
B = np.random.randint(0, 100, 10)
print(np.array_equal(A, B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [231]:
A = np.arange(5)
A.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [246]:
C = np.random.randint(0, 200, (10, 2))
cart_to_polar = lambda x, y: ( np.linalg.norm([x,y]), np.arctan2(y, x) )
C_p = np.empty((10, 2))
for i in range(10):
    C_p[i] = cart_to_polar(C[i, 0], C[i, 1])
print(C)
print(C_p)

[[131   2]
 [118  75]
 [ 82 107]
 [ 18 126]
 [ 91   6]
 [102  76]
 [138 103]
 [ 54  25]
 [194 186]
 [  9 105]]
[[1.31015266e+02 1.52659895e-02]
 [1.39817739e+02 5.66180671e-01]
 [1.34807270e+02 9.16909835e-01]
 [1.27279221e+02 1.42889927e+00]
 [9.11975877e+01 6.58387693e-02]
 [1.27200629e+02 6.40356465e-01]
 [1.72200465e+02 6.41178233e-01]
 [5.95063022e+01 4.33581484e-01]
 [2.68760116e+02 7.64348641e-01]
 [1.05385008e+02 1.48529103e+00]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [249]:
y = np.random.random(10)
y[y.argmax()] = 0
print(y)

[0.12076331 0.64186352 0.19780597 0.71316337 0.27454792 0.91951694
 0.07314229 0.         0.22223607 0.53090014]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [251]:
Z = np.ones((11, 11), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,11), np.linspace(0,1,11))
print(Z)

[[(0. , 0. ) (0.1, 0. ) (0.2, 0. ) (0.3, 0. ) (0.4, 0. ) (0.5, 0. )
  (0.6, 0. ) (0.7, 0. ) (0.8, 0. ) (0.9, 0. ) (1. , 0. )]
 [(0. , 0.1) (0.1, 0.1) (0.2, 0.1) (0.3, 0.1) (0.4, 0.1) (0.5, 0.1)
  (0.6, 0.1) (0.7, 0.1) (0.8, 0.1) (0.9, 0.1) (1. , 0.1)]
 [(0. , 0.2) (0.1, 0.2) (0.2, 0.2) (0.3, 0.2) (0.4, 0.2) (0.5, 0.2)
  (0.6, 0.2) (0.7, 0.2) (0.8, 0.2) (0.9, 0.2) (1. , 0.2)]
 [(0. , 0.3) (0.1, 0.3) (0.2, 0.3) (0.3, 0.3) (0.4, 0.3) (0.5, 0.3)
  (0.6, 0.3) (0.7, 0.3) (0.8, 0.3) (0.9, 0.3) (1. , 0.3)]
 [(0. , 0.4) (0.1, 0.4) (0.2, 0.4) (0.3, 0.4) (0.4, 0.4) (0.5, 0.4)
  (0.6, 0.4) (0.7, 0.4) (0.8, 0.4) (0.9, 0.4) (1. , 0.4)]
 [(0. , 0.5) (0.1, 0.5) (0.2, 0.5) (0.3, 0.5) (0.4, 0.5) (0.5, 0.5)
  (0.6, 0.5) (0.7, 0.5) (0.8, 0.5) (0.9, 0.5) (1. , 0.5)]
 [(0. , 0.6) (0.1, 0.6) (0.2, 0.6) (0.3, 0.6) (0.4, 0.6) (0.5, 0.6)
  (0.6, 0.6) (0.7, 0.6) (0.8, 0.6) (0.9, 0.6) (1. , 0.6)]
 [(0. , 0.7) (0.1, 0.7) (0.2, 0.7) (0.3, 0.7) (0.4, 0.7) (0.5, 0.7)
  (0.6, 0.7) (0.7, 0.7) (0.8, 0.7) (0.9, 0.7) (1. 

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [253]:
X = np.random.randint(0, 100, 10)
Y = np.random.randint(0, 100, 10)
C = 1/np.subtract.outer(X, Y)
print(C)

[[ 0.03703704 -0.02777778 -0.09090909  0.03571429  0.04       -0.06666667
  -0.25       -0.02564103 -0.02222222 -0.02325581]
 [ 0.02631579 -0.04               inf  0.02564103  0.02777778 -0.25
   0.14285714 -0.03571429 -0.02941176 -0.03125   ]
 [ 0.05882353 -0.02173913 -0.04761905  0.05555556  0.06666667 -0.04
  -0.07142857 -0.02040816 -0.01818182 -0.01886792]
 [ 0.01408451  0.125       0.03030303  0.01388889  0.01449275  0.03448276
   0.025       0.2        -1.          1.        ]
 [-0.25       -0.01492537 -0.02380952 -0.33333333 -0.16666667 -0.02173913
  -0.02857143 -0.01428571 -0.01315789 -0.01351351]
 [ 0.01960784 -0.08333333  0.07692308  0.01923077  0.02040816  0.11111111
   0.05       -0.06666667 -0.04761905 -0.05263158]
 [ 0.09090909 -0.01923077 -0.03703704  0.08333333  0.11111111 -0.03225806
  -0.05       -0.01818182 -0.01639344 -0.01694915]
 [-1.         -0.015625   -0.02564103         inf -0.33333333 -0.02325581
  -0.03125    -0.01492537 -0.01369863 -0.01408451]
 [ 0.3333333

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [255]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [260]:
np.set_printoptions(threshold=np.nan)
A = np.random.random((10,8))
print(A)

[[0.99211898 0.31920745 0.86072144 0.53867292 0.93533114 0.05878721
  0.99032965 0.35276671]
 [0.36467962 0.13087049 0.56335105 0.59452577 0.81127705 0.28457852
  0.39691471 0.00921653]
 [0.1919319  0.51401607 0.2896448  0.55402845 0.54474371 0.9968705
  0.44293119 0.36957228]
 [0.81995156 0.79206693 0.39607161 0.2917984  0.25244885 0.25180953
  0.33975625 0.06859082]
 [0.47132584 0.96612991 0.21368387 0.32142648 0.99033084 0.41850021
  0.09919709 0.22014627]
 [0.17947773 0.26770395 0.82712734 0.5673638  0.71754014 0.75489081
  0.08154975 0.02425055]
 [0.18043894 0.86414132 0.69432563 0.12101317 0.40487286 0.80491588
  0.90632925 0.32400322]
 [0.21786531 0.2389352  0.71807543 0.17668643 0.01867819 0.19317359
  0.47819565 0.94844919]
 [0.73225745 0.71169803 0.08840853 0.75907189 0.67776213 0.41039873
  0.75970354 0.82361297]
 [0.71975064 0.84229533 0.41259226 0.01795266 0.75289543 0.51365929
  0.77114787 0.87615136]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [263]:
X = np.random.randint(0, 100, 15)
scalar = 14
print(X[(np.abs(X- scalar)).argmin()])

11


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [266]:
Y = np.ones((5, 5), [('position', [('x', float, 1), ('y', float, 1)]), 
                  ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(Y)

[[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
  ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
  ((1., 1.), (1., 1., 1.))]
 [((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
  ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
  ((1., 1.), (1., 1., 1.))]
 [((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
  ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
  ((1., 1.), (1., 1., 1.))]
 [((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
  ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
  ((1., 1.), (1., 1., 1.))]
 [((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
  ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
  ((1., 1.), (1., 1., 1.))]]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [282]:
Z = np.random.random((10, 2))
distances = np.empty((10, 10))
for i in range(10):
    for j in range(10):
        distances[i, j] = np.sqrt((Z[i, 0] - Z[j, 0])**2 +(Z[i, 1] - Z[j, 1])**2)
print(distances)

[[0.         0.17745687 0.78703783 0.85036472 0.52742917 0.24504926
  0.67039123 0.51161576 0.38123123 0.59982647]
 [0.17745687 0.         0.73342969 0.86840649 0.68554305 0.07624082
  0.5743604  0.52363937 0.43745998 0.51021465]
 [0.78703783 0.73342969 0.         0.34287931 0.89056443 0.76492884
  0.22842109 0.33851191 0.4952234  0.25200219]
 [0.85036472 0.86840649 0.34287931 0.         0.7343524  0.92344431
  0.53885946 0.3455502  0.47323812 0.52692117]
 [0.52742917 0.68554305 0.89056443 0.7343524  0.         0.76086477
  0.91092226 0.55787447 0.42429291 0.84479184]
 [0.24504926 0.07624082 0.76492884 0.92344431 0.76086477 0.
  0.58880566 0.58129379 0.50644514 0.52975356]
 [0.67039123 0.5743604  0.22842109 0.53885946 0.91092226 0.58880566
  0.         0.37198532 0.4867725  0.07233231]
 [0.51161576 0.52363937 0.33851191 0.3455502  0.55787447 0.58129379
  0.37198532 0.         0.16061146 0.31738196]
 [0.38123123 0.43745998 0.4952234  0.47323812 0.42429291 0.50644514
  0.4867725  0.16061

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [283]:
A = np.ones(4, dtype=np.float32)
A = A.astype(np.int32, copy=False)
print(A)

[1 1 1 1]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [284]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
T = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(T)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [292]:
X = np.arange(9).reshape(3,3)
for i, x in np.ndenumerate(X):
    print(i, x)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [306]:
G = np.random.normal(5, 15, (5, 5))
print(G)

[[ -3.79572778   7.50283859 -19.50341852   6.58626816  -3.20959284]
 [ -0.76916097  -4.02784228   0.80221492  -9.27328216  15.08692416]
 [ -8.62348802   5.57481569  -3.12848666  25.34704799  14.30318325]
 [ 27.71834435  20.35888792  15.74898863  22.38691587  -2.99712737]
 [  9.32709674 -12.16038226   3.08213243 -30.9516483    7.11311989]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [309]:
n = 6
p =8
A = np.zeros((n, n))
np.put(A, np.random.choice(range(n**2), p, replace=False), 1)
print(A)

[[0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [315]:
A = np.arange(9).reshape((3, 3))
A = A - A.mean(axis = 1, keepdims = True)
print(A)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [316]:
A = np.random.random((3, 3))
print(A)
print(A[A[:,0].argsort()])

[[0.76136171 0.74039549 0.43544909]
 [0.2764915  0.92580841 0.16763499]
 [0.31095985 0.82002639 0.68479525]]
[[0.2764915  0.92580841 0.16763499]
 [0.31095985 0.82002639 0.68479525]
 [0.76136171 0.74039549 0.43544909]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [339]:
X = np.random.randint(-2,2, (3,12))
print(X)
print((~X.any(axis=0)).any())

[[-1  0  0  1  0 -2  0 -2 -2  1  0  1]
 [ 0 -2 -1  0 -2  0  0  1 -1  0  0 -2]
 [ 0  1 -1 -2 -1 -2 -2  1 -2  1 -1  0]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [340]:
A = np.random.uniform(0,1,10)
v = 0.5
c = A.flat[np.abs(A-v).argmin()]
print(c)

0.5140885059522031


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [348]:
X = np.random.random((10,10))
I = np.random.randint(0,len(X),10)
np.add.at(X, I, 1)
print(X)

[[0.21130186 0.88383615 0.12098866 0.07423955 0.29473609 0.81478376
  0.51953704 0.28117168 0.86346891 0.71151335]
 [1.25344476 1.40440053 1.30818511 1.66641927 1.52709787 1.23580777
  1.18310336 1.71901848 1.40131639 1.69586723]
 [0.75954416 0.29149988 0.62945051 0.40399541 0.8369141  0.18547677
  0.17230072 0.14041534 0.21813003 0.95774431]
 [3.55427456 3.42898001 3.2750121  3.11558878 3.39537275 3.84387248
  3.93781552 3.26049083 3.97853639 3.6124286 ]
 [1.16289593 1.48295699 1.3627402  1.3653723  1.42550545 1.16336992
  1.88896484 1.6334398  1.10755821 1.34820512]
 [0.7453315  0.24814519 0.33272382 0.67096892 0.44619019 0.40595807
  0.48953289 0.13175377 0.21972141 0.45656254]
 [2.60463897 2.25144999 2.18344597 2.11293328 2.31556678 2.67830535
  2.74905721 2.36102764 2.62096751 2.46214277]
 [3.90140561 3.51819154 3.50499229 3.65329324 3.47262485 3.35703292
  3.12410371 3.94137269 3.11290535 3.50853823]
 [0.2958683  0.41473986 0.73483542 0.53983959 0.31225268 0.98536973
  0.60952153

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)